CREATE TABLE EDITIONS (
    EDITION_ID int AUTO_INCREMENT PRIMARY KEY
    ,EDITION_TITLE nvarchar(255)
    ,AUTHOR_ID int
    ,TEXT_ID int
    ,EDITION_EDITOR nvarchar(255)
    ,EDITION_TRANSLATOR nvarchar(255)
    ,EDITION_PUBLISHER nvarchar(255)
    ,EDITION_PUBLICATION_DATE datetime
    ,EDITION_PUBLICATION_YEAR int
    ,EDITION_ISBN nvarchar(255)
    ,EDITION_ISBN13 nvarchar(255)
    ,EDITION_LENGTH int
    ,EDITION_LANGUAGE nvarchar(255)
    ,EDITION_BINDING nvarchar(255)
)