CREATE TABLE TEXTS (
TEXT_ID int AUTO_INCREMENT PRIMARY KEY
,TEXT_TITLE nvarchar(255)
,TEXT_AUTHOR nvarchar(255)
,AUTHOR_ID int
,TEXT_TYPE nvarchar(255)
,TEXT_GENRE nvarchar(255)
,TEXT_LANGUAGE nvarchar(255)
,TEXT_ORIGINAL_PUBLICATION_DATE datetime
,TEXT_ORIGINAL_PUBLICATION_YEAR int
,TEXT_ORIGINAL_PUBLICATION_MONTH int
,TEXT_ORIGINAL_PUBLICATION_DAY int
,TEXT_ORIGINAL_PUBLICATION_PUBLISHER nvarchar(255)
,TEXT_ORIGINAL_PUBLICATION_PUBLISHER_LOC nvarchar(255)
,TEXT_ORIGINAL_PUBLICATION_TYPE nvarchar(255)
,TEXT_ORIGINAL_PUBLICATION_LENGTH int
,TEXT_ORIGINAL_PUBLICATION_LENGTH_TYPE nvarchar(255)
,TEXT_WRITING_START int
,TEXT_WRITING_END int
)