CREATE TABLE IF NOT EXISTS AUTHORS2 (
AUTHOR_ID SERIAL PRIMARY KEY
,AUTHOR_NAME varchar(255)
,AUTHOR_POSITIONS varchar(255)
,AUTHOR_NAME_LANGUAGE varchar(255)
,AUTHOR_BIRTH_DATE varchar(255)
,AUTHOR_BIRTH_CITY varchar(255)
,AUTHOR_BIRTH_COUNTRY varchar(255)
,AUTHOR_BIRTH_COORDINATES varchar(255)
,AUTHOR_BIRTH_YEAR int --CHECK (AUTHOR_BIRTH_YEAR<= AUTHOR_DEATH_YEAR OR AUTHOR_DEATH_YEAR IS NULL)
,AUTHOR_BIRTH_MONTH int
,AUTHOR_BIRTH_DAY int
,AUTHOR_DEATH_DATE varchar(255)
,AUTHOR_DEATH_CITY varchar(255)
,AUTHOR_DEATH_COUNTRY varchar(255)
,AUTHOR_DEATH_COORDINATES varchar(255)
,AUTHOR_DEATH_YEAR int
,AUTHOR_DEATH_MONTH int
,AUTHOR_DEATH_DAY int
,AUTHOR_NATIONALITY varchar(255)
,AUTHOR_GENDER varchar(255)
,AUTHOR_FLORUIT varchar(255)
);
