CREATE TABLE AUTHORS (
AUTHOR_ID int AUTO_INCREMENT PRIMARY KEY
,AUTHOR_NAME nvarchar(255)
,AUTHOR_POSITIONS nvarchar(255)
,AUTHOR_NAME_LANGUAGE nvarchar(255)
,AUTHOR_BIRTH_DATE datetime
,AUTHOR_BIRTH_CITY nvarchar(255)
,AUTHOR_BIRTH_COUNTRY nvarchar(255)
,AUTHOR_BIRTH_COORDINATES nvarchar(255)
,AUTHOR_BIRTH_YEAR int
,AUTHOR_BIRTH_MONTH int
,AUTHOR_BIRTH_DAY int
,AUTHOR_DEATH_DATE datetime
,AUTHOR_DEATH_CITY nvarchar(255)
,AUTHOR_DEATH_COUNTRY nvarchar(255)
,AUTHOR_DEATH_COORDINATES nvarchar(255)
,AUTHOR_DEATH_YEAR int
,AUTHOR_DEATH_MONTH int
,AUTHOR_DEATH_DAY int
,AUTHOR_NATIONALITY nvarchar(255)
,AUTHOR_GENDER nvarchar(255)
,AUTHOR_FLORUIT nvarchar(255)
)
