CREATE TABLE EDITIONS (
    EDITION_ID SERIAL PRIMARY KEY
    ,EDITION_TITLE varchar(255)
    ,AUTHOR_ID int REFERENCES AUTHORS (author_id)
    ,TEXT_ID int
    ,EDITION_EDITOR varchar(255)
    ,EDITION_TRANSLATOR varchar(255)
    ,EDITION_PUBLISHER varchar(255)
    ,EDITION_PUBLICATION_DATE date
    ,EDITION_PUBLICATION_YEAR int
    ,EDITION_ISBN varchar(255)
    ,EDITION_ISBN13 varchar(255)
    ,EDITION_LENGTH int
    ,EDITION_LANGUAGE varchar(255)
    ,EDITION_BINDING varchar(255)
)