CREATE TABLE TEXTS (
TEXT_ID SERIAL PRIMARY KEY
,TEXT_TITLE varchar(255)
,TEXT_AUTHOR varchar(255)
,AUTHOR_ID int
,TEXT_TYPE varchar(255)
,TEXT_GENRE varchar(255)
,TEXT_LANGUAGE varchar(255)
,TEXT_ORIGINAL_PUBLICATION_DATE varchar(255)
,TEXT_ORIGINAL_PUBLICATION_YEAR int
,TEXT_ORIGINAL_PUBLICATION_MONTH int
,TEXT_ORIGINAL_PUBLICATION_DAY int
,TEXT_ORIGINAL_PUBLICATION_PUBLISHER varchar(255)
,TEXT_ORIGINAL_PUBLICATION_PUBLISHER_LOC varchar(255)
,TEXT_ORIGINAL_PUBLICATION_TYPE varchar(255)
,TEXT_ORIGINAL_PUBLICATION_LENGTH int
,TEXT_ORIGINAL_PUBLICATION_LENGTH_TYPE varchar(255)
,TEXT_WRITING_START int
,TEXT_WRITING_END int
)